### ISSUE TITLE
Gulp does not compile

### ISSUE THREAD

**Issue by gaurav21r** [benjamine/jsondiffpatch#125]
On Win10, running `gulp bundle` gives this error:

```
D:\xampp\htdocs\experiments\jsondiffpatch>gulp bundle
browserifying with minifyify
[19:34:32] Using gulpfile D:\xampp\htdocs\experiments\jsondiffpatch\gulpfile.js
[19:34:32] Starting 'clean'...
[19:34:32] Finished 'clean' after 3.38 ms
[19:34:32] Starting 'bundle-jsondiffpatch'...
[19:34:33] 'bundle-jsondiffpatch' errored after 842 ms
[19:34:33] Error: Minifyify: opts.output is required since no callback was given
    at Browserify.bundle.bundle (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\minifyify\lib\index.js:55:13)
    at createBundle (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\fiberglass\src\gulp\tasks\util\bundler.js:108:30)
    at bundlify (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\fiberglass\src\gulp\tasks\util\bundler.js:160:14)
    at Gulp.bundleTask (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\fiberglass\src\gulp\tasks\util\bundler.js:171:5)
    at module.exports (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\orchestrator\index.js:214:10)
    at D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\orchestrator\index.js:279:18
    at finish (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\orchestrator\lib\runTask.js:21:8)
    at cb (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\orchestrator\lib\runTask.js:29:3)
    at CB (D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\rimraf\rimraf.js:68:5)
    at D:\xampp\htdocs\experiments\jsondiffpatch\node_modules\rimraf\rimraf.js:91:16
    at FSReqWrap.oncomplete (fs.js:82:15)
```

The error seems to indicate that we should somehow specify the output directory? But the docs don't indicate that. I went looking for the `Gulpfile` to see what's hapenning, but I got utterly confused since something called `fiberglass` is being used to define all the Gulp tasks in an automated way.

Please help! I need to compile the patch given at #119 urgently! :disappointed:

**Comment by benjamine** [comment]
this looks like a windows compatibility problem with `minifyify` module, and I don't have a windows machine to test this.
if it helps, you don't need to bundle it on your machine, you can use bundled version already in `/public/` folder, or if you need a modified version, you can build your fork in travis or circleci.

**Comment by dannypaz** [comment]
@benjamine I am receiving the same error with MacOS.

**Comment by dannypaz** [comment]
@benjamine That was it. I switched to Node 4.4.3 (stable) and was able to compile.
